project:
  type: website
  output-dir: docs
  
website:
  title: "DACSS604 Fall24"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/zeying0314/DACSS604
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Zeying Guo"

format:
  html:
    theme: cerulean
    toc: true

editor: source

resources: 
  - "files/**"
